### ISSUE TITLE
client.Flush() doesn't flush synchronously

### ISSUE THREAD

**Issue by rerorero** [DataDog/datadog-go#105]
Hi.
I'm facing a strange behavior in Flush(). When I run the code below, it doesn't finish flushing then results in deadlock failure.
https://play.golang.org/p/90sBE2ed9dV
Can someone help?

**Comment by arbll** [comment]
Hi @rerorero, 
There was indeed a bug with custom writers that would lead to the majority of the metrics, fixing it in https://github.com/DataDog/datadog-go/pull/106. 

Regarding your test 
```go
if buf.Len() == 0 {
```
would never be true after the flush. This buffer represents the output of the client in your scenario so a flush should result in this buffer containing 3000 formatted metrics, not being empty.
That said, because of the bug above a good chunk of those 3000 metrics would get dropped. Once it's fixed you should get them all in `buf`.

LMK if you have questions,
Arthur

**Comment by rerorero** [comment]
@arbll thank you for reply!  sorry, I had a mistake in the code. `buf.Len() == 0` is wrong.

But even after fixing my code, I still see an another strange things.

With [this code](https://play.golang.org/p/EFCVCs4mcrN) looks like Flush() doesn't flush synchronously. Is this expected?

I checked  #106 but it doesn't affect the code because I don't pass any options and [resolveOptions](https://github.com/DataDog/datadog-go/blob/master/statsd/statsd.go#L242) would set the default values.

**Comment by arbll** [comment]
@rerorero this library starts dropping metrics when it's inner queues are full. This might seem surprising but this is a requirement to ensure that the app making calls to this library won't ever be blocked for a long time.

The bug in #106 leads to extremely small queues (1 element) when you are using custom writers (not udp/uds) leading to metrics being dropped very easily.

This is most likely why you don't have all the metrics you are expecting in the final buffer after the flush.

**Comment by rerorero** [comment]
I see, thank you for kind explanation.
