### ISSUE TITLE
Invalid metric names not escaped

### ISSUE THREAD

**Issue by mperham** [DataDog/datadog-go#125]
Howdy, I'm using dogstatsd-go 3.3.0 and seeing this error:

```
ERROR | (pkg/dogstatsd/server.go:298 in parsePacket) | Dogstatsd: error parsing metrics: invalid metric value for
"faktory.jobs.BareStripe::WebhookReceiverWorker.perform:23.737378|ms|#env:production,env:production,env:production,env:production,env:production,queue:import_stripe_webhooks,jobtype:BareStripe::WebhookReceiverWorker"
```

(the env:production repetition is a separate issue) 

Any idea why the API is sending metric lines that can't be parsed by the agent?  I would expect either an error or for this API to escape any illegal characters before sending over the network. I couldn't find any documentation in the README or linked that talks about allowed characters in metric and tag names/values and I couldn't find any code which escaped characters in this repo.

**Comment by mperham** [comment]
Ok, I found this link but I can't find where the client library performs this escaping for me.  Does it?

https://docs.datadoghq.com/developers/metrics/#naming-custom-metrics

I assume the issue is `BareStripe::WebhookReceiverWorker` in the name.  Since this form of metric name has been deprecated in my system, I'm just going to remove those metrics. I'll leave this open because the client API can still be improved.

**Comment by hush-hush** [comment]
Hi @mperham,

Yes the issue comes from the metric name. We do not escape metric name for performance reason. Vetting all metric name when sending over 200k metrics/s would increase the latency of the package greatly.

There are two main reasons why escaping is a performance concern:
- some customers submit metrics from hot paths. Increasing latency would have direct performance impact on their applications.
- Doing it on a separate thread while buffering it would increase CPU utilization: also affecting their application.

That being said, I will update the documentation of the README to reflect this.

I'll close this issue but feel free to reopen it or a new one if needed.
