### ISSUE TITLE
Buffered client does not respect UDP packet length limits

### ISSUE THREAD

**Issue by glasser** [DataDog/datadog-go#4]
UDP packets have a max length of ~64K, but the buffering logic in `statsd.NewBuffered` doesn't make any effort to keep single messages below this length.

**Comment by phoet** [comment]
i guess we were running into this issue. or at least some other weird behavior of the buffered client resulting in a bazillion tags screwing up our metrics:

<img width="409" alt="screen shot 2015-10-15 at 12 02 47" src="https://cloud.githubusercontent.com/assets/48745/10510679/9dc6568e-7334-11e5-9d18-db4d5b9bcf6b.png">

our assumption is that the last message is truncated resulting in arbitrary tags.

**Comment by glasser** [comment]
Yes, that is the symptom.

**Comment by mat** [comment]
In our case, removing command buffering not only produces correct results but also improves throughput/load by roughly 2x. Also the Datadog/statsd daemon in this scenario seems to hold up fine, too.

https://github.com/mat/heroku-datadog-drain-go

**Comment by sschepens** [comment]
If anyone's interested, i fixed this in pull request [7](https://github.com/DataDog/datadog-go/pull/7)

**Comment by phoet** [comment]
:+1:

**Comment by mat** [comment]
Nice, thanks!

**Comment by sschepens** [comment]
Right now it makes the assumption that the network's MTU is 1500, that is not always true, it could be smaller or greater.
One solution would be to inspect all [Interfaces](https://golang.org/pkg/net/#Interfaces) and get the smaller MTU of all. Knowing which interface exactly a connection will be using I believe is much harder or impossible.
Another solution would be to allow users to specify their MTU and with that value calculate the maximum packet size.

**Comment by mat** [comment]
@sschepens I have a feeling the max payload size is too much dependent on the underlying network and such for it to be hardcoded. So while assuming an MTU of 1500 is a good idea I'd say it can't hurt to introduce an env variable for overriding, too.

Oh, and Happy New Year 🎉 :)

**Comment by phoet** [comment]
from my understanding of TCP/IP the MTU should not matter as UDP packets that don't fit the MTU would be fragmented on the IP layer? this is also what [this stackoverflow question](http://stackoverflow.com/questions/3712151/udp-ip-fragmentation-and-mtu) indicates.

**Comment by sschepens** [comment]
@phoet I thought so too. I tested with a size of 65507 metrics continued to get cut, maybe it's because IP headers can be greater than 20bytes, up to 60bytes, I haven't tested lowering the maximum size to fit with a 60byte header.
Another issue with big datagrams might be something that is actually [linked to](http://linux.derkeiler.com/Newsgroups/comp.os.linux.networking/2004-02/0873.html) in the question you linked. IP does not provide delivery guarantees, TCP does, so packets can be lost, if a packet belonging to the UDP datagram is lost I don't really know what happens to the UDP datagram, it's probably discarded.
This could lead to much greater losses than sending smaller datagrams I think.
I don't really know what the best solution to this problem is.

**Comment by sschepens** [comment]
Also, the standard defines that a packet will not be fragmented if it's size is less than 576, this is great as it ensures this would work on every network, but it provides less performance for networks that support higher MTU

**Comment by phoet** [comment]
i would love to get an experts comment on this, because my actual network protocol knowledge never made it past what i learned in university, but from what i "think" i understood is that

* MTU is discovered on IP level through path algorithms so there is minimal packet loss
* IP layer handles assembly/disassembly of datagrams into packets
* if a package is lost, the datagram is discarded
  * TCP resends all packets of a datagram
  * UDP :fire: 

if this is "true" i would stick to keep the message within the maximum size of a UDP packets minus some buffer

> A field that specifies the length in bytes of the UDP header and UDP data. The minimum length is 8 bytes because that is the length of the header. The field size sets a theoretical limit of 65,535 bytes (8 byte header + 65,527 bytes of data) for a UDP datagram. The practical limit for the data length which is imposed by the underlying IPv4 protocol is 65,507 bytes (65,535 − 8 byte UDP header − 20 byte IP header).[2]

**Comment by sschepens** [comment]
I think it works that way, except for 
> MTU is discovered on IP level through path algorithms so there is minimal packet loss
MTU is discovered but IP does a best effort to prevent packet loss and has nothing to do with MTU itself. Packet loss can happen on best networks too.
We could use maximum packet size minus 8 byte UDP header and 60 byte maximum IP header size, that would leave us with 65467 bytes for payload.
The only downside I see is that losing a single packet for that huge UDP datagram leads to the loss of the hole datagram, while if sending multiple smaller datagrams one would lose less information as potentially only a single small datagram was lost, I believe that's why people recommend trying not to fragment UDP datagrams.

**Comment by truthbk** [comment]
Issue addressed in #11 - we attempt to keep frames under the typical MTU size of 1500. If a command is >1500 we send it in its own frame and hope fragmentation won't result in the command being dropped (but no guarantees can be made due to the UDP transport). Finally, if a message is >64K it gets dropped for now. We can maybe truncate the event text in a future PR.
