### ISSUE TITLE
Client doesn't reconnect if agent restarts

### ISSUE THREAD

**Issue by AngerM** [DataDog/datadog-go#54]
We've been using datadog in a kubernetes environment. We have datadog agent running as a daemonset and the client in our go apps running inside kubes on the cluster. However if the agent restarts (due to a daemonset config change, upgrade, etc) we don't see any metrics flowing even after the agent comes back online. It would be great if the client could automatically attempt to reconnect in the background so we don't have to roll the app to get stats flowing again.

**Comment by truthbk** [comment]
@AngerM thank you for reporting this and apologies for the slow response. We will try to address this as soon as possible. That said, if this this is urgent to anybody and a PR cannot be submitted by the community at large, please let us know so we can prioritize accordingly.

**Comment by truthbk** [comment]
@AngerM this is pretty embarrassing. Sorry this fell through the cracks. We'll be looking into it this week. Sorry again.

**Comment by truthbk** [comment]
@AngerM, Oh OK that's not the scenario I was expecting. Given that by definition (from the daemonset) there will be an agent running on every node in the cluster, one would a) expect the IP to not change b) given that UDP is stateless, the same socket we opened on the client should still be valid so long as the container is listening. 

The one thing I believe is that if the IP does change for the agent container, that change I don't think will propagate to the app's container as the environment variable is set when the application is started. You would typically need to restart that pod for the new ip address to be available in the container. 

Good news is that it should be easy to reproduce. I had started work on a PR assuming this was going to have to do with some DNS resolution issue. Which is another scenario we weren't contemplating in the client. Thanks for the quick response by the way.

**Comment by AngerM** [comment]
Awesome. I agree, but I think its an implementation detail of the golang udp dialer. It doesn't treat the connection as stateless, so if an error occurs (ie the datadog agent is down) you have to 'redial' before sending more packets.

**Comment by truthbk** [comment]
@AngerM I don't think it's necessarily an implementation detail in the dialer. UDP is a fire and forget protocol. The only way to know if the other end is listening is by being aware of the ICMP error responses (provided they can get through firewalls, etc) when the UDP packets hit a host that has a closed port, or if the IP address is not reachable. There's no real way, other than that, to tell if an error has occurred - that's the nature of UDP. 

Processing the ICMP responses is probably not something we're going to be doing on the client because it would add quite a bit of overhead (ie. looking at all IP packets coming in at an interface to filter out ICMP responses - though maybe we could set something up with a BPF filter that wouldn't be so bad - and then parsing the ICMP responses). 

We could do something about it if DNS was involved by periodically checking for changes in the UDP resolution, and "re-dialing" (this isn't even a thing in UDP, but basically setting up a new updated socket).

**Comment by truthbk** [comment]
@AngerM any chance you can paste your daemonset configuration YAML here? Feel free to redact anything you're not comfortable sharing. Or if you'd rather not, would you like to share by email?

**Comment by AngerM** [comment]
It's basically the one you guys provide in your setup example. just `xxx`d out a few things
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: xxx
  generation: xxx
  labels:
    app: datadog-agent
  name: datadog-agent
  namespace: default
  resourceVersion: "xxx"
  selfLink: /apis/extensions/v1beta1/namespaces/default/daemonsets/datadog-agent
  uid: xxx
spec:
  revisionHistoryLimit: xxx
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      containers:
      - env:
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
          value: "1"
        - name: DD_API_KEY
          value: xxx
        - name: KUBERNETES
          value: "yes"
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: datadog/agent:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: datadog-agent
        ports:
        - containerPort: 8125
          hostPort: 8125
          name: dogstatsdport
          protocol: UDP
        - containerPort: 8126
          hostPort: 8126
          name: traceport
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersocket
        - mountPath: /host/proc
          name: procdir
          readOnly: true
        - mountPath: /host/sys/fs/cgroup
          name: cgroups
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersocket
      - hostPath:
          path: /proc
          type: ""
        name: procdir
      - hostPath:
          path: /sys/fs/cgroup
          type: ""
        name: cgroups
  templateGeneration: 3
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100
    type: RollingUpdate
```

**Comment by truthbk** [comment]
Hi @AngerM I was able to get metrics flowing after a restart with no issues in a very similar scenario (I'm using the stock daemonset configuration). I wrote a dummy app that submits dogstatsd metrics (container available here: https://hub.docker.com/r/jfullaondo/dsd-sampler, code here: https://gist.github.com/truthbk/e91a567c3230da357f2836d54a2a1956). I did run this on `minikube`, but I wouldn't expect much difference in a multi-node cluster since each node would typically have its  daemonset pod with the agent listening.

daemonset config:
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      containers:
      - image: datadog/agent:latest
        imagePullPolicy: Always
        name: datadog-agent
        ports:
          - containerPort: 8125
            hostPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            hostPort: 8126
            name: traceport
            protocol: TCP
        env:
          - name: DD_API_KEY
            value: <API_KEY_HERE>
          - name: DD_LOG_LEVEL
            value: trace 
          - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
            value: "true"
          - name: DD_APM_ENABLED
            value: "true"
          - name: KUBERNETES
            value: "yes"
          - name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
```

dummy app deployment yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsd-sampler 
  labels:
    app: dsd-sampler
spec:
  selector:
    matchLabels:
      app: dsd-sampler 
  template:
    metadata:
      labels:
        app: dsd-sampler 
    spec:
      containers:
      - name: dsd-random-sampler 
        image: jfullaondo/dsd-sampler:beta
        imagePullPolicy: Always
        env:
          - name: DOGSTATSD_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DOGSTATSD_HOST_PORT
            value: "8125"
```

Had no issues across multiple restarts.

Would you mind sending over some debugging info?
```bash
kubectl exec -it <datadog-agent-pod> /bin/bash
(in container)
apt-get install net-tools
netstat -ntplu
```

If you want to verify the packets are making it to the agent container:
```bash
apt-get install tcpdump
tcpdump -iany -s0 -vvv -A udp port 8125
```

Across multiple restarts, even after removing the daemonset and re-creating it, the metrics continued to flow in. This would be the expected behavior with the client as it currently stands due to the stateless nature of UDP. 

This is also the behavior I got just running a similar scenario manually just with docker, no k8s. It just recovered automatically.

**Comment by truthbk** [comment]
Great investigation here https://github.com/DataDog/dogstatsd-csharp-client/issues/64#issuecomment-409021831 from @brantburnett, as expected this is more of a networking environment change and iptables NAT behavior more than an issue with the actual clients.

**Comment by truthbk** [comment]
@AngerM please take a look at https://github.com/DataDog/dogstatsd-csharp-client/issues/64 if you want some more details, and the ongoing discussion there. This is most probably an issue with K8s CNI and not with our clients. Essentially, there's a `conntrack` session being created that _"hijacks"_ the UDP packets that are expected at the dogstatsd `datadog-agent` container. We're still not 100% sure if the problem is with the CNI per-se, or if its a legit race-condition while waiting for the agent container to come back up and the host "thinking" those UDP packets being received are actually for the host (hence the bad `conntrack` session, if that is the case). The weird bit there is it would be surprising if a `conntrack` session would be created to a port we're not listening at... we might have to read/investigate that a little bit.

TLDR; not really an issue on the client side, and not much we can do to that regard.

**Comment by AngerM** [comment]
Read through that thread. Thanks!
